### ISSUE TITLE
Add meta fields to each task

### ISSUE THREAD

**Issue by jakelowen** [gpsimpact/census-relational-organizing-frontend#110]
Colin: 

> Can we add a "contact method" dropdown at the bottom of each task, to indicate whether that particular task was done in-person, over the phone, etc., and a "date completed" calendar function? This ideally would also automatically add a "canvassed" contact attempt to the contact history for that particular day.

Likely has big backend implications, but I'll let you tell me what you need here.

**Comment by jrazmi** [comment]
I'll give a test run on just adding those to the json fields.  Select field for contact attempt and then I'll need a new type for date field.  Will let you know if needs anything from the backend.

**Comment by jrazmi** [comment]
@jakelowen can you add calendar to the form field enum.

Error: GraphQL error: Expected a value of type "FORM_FIELD_TYPE_ENUM" but received: "calendar"

**Comment by jrazmi** [comment]
`  {
    "name": "contact_method",
    "type": "radio",
    "label": "Contact Method for this task",
    "selectOptions": [
      {
        "label": "IN PERSON",
        "value": "IN_PERSON"
      },
      {
        "label": "PHONE",
        "value": "PHONE"
      }
    ]
  },
  {
    "name": "date_completed",
    "type": "date",
    "label": "Date Completed: MM/DD/YY",
    "placeholder": "Date Completed: MM/DD/YY"
  }`

**Comment by jrazmi** [comment]
I closed it as the code is in there, but reopened because we'll need to add to each forms form fields the above json

**Comment by jakelowen** [comment]
@jrazmi - Is that something I can help with?

**Comment by jrazmi** [comment]
@jakelowen - yep yep.  cleaning up a couple of smaller issues and then I'm going to deploy these to prod.  Don't want to add in just yet, but I'll ping you.

**Comment by jakelowen** [comment]
Added to DB. Working.
