### ISSUE TITLE
Basic user dashboard enhancement

### ISSUE THREAD

**Issue by jakelowen** [gpsimpact/census-relational-organizing-frontend#113]
> In the same way as admins have a data report out for all teams, and teams have a report out for all their trusted messengers, can individual users with no permissions have a dashboard that shows their data for their contacts?

Don't they already? Any idea what this means?

**Comment by jrazmi** [comment]
@jakelowen yeah - they do... don't know what it means.   That being said.  I'm about to wipe all of those reports to implement the task specific reporting so i'll double check.
