### ISSUE TITLE
Test/default contact attempts/notes/history are still being added to new contacts. Can this please be disabled? Is there anyway to automatically delete the test data from all currently entered contacts?

### ISSUE THREAD

**Issue by jakelowen** [gpsimpact/census-relational-organizing-frontend#126]
From Colin.

No idea. Let's investigate.

**Comment by jrazmi** [comment]
![Screen Shot 2020-01-02 at 11 05 50 AM](https://user-images.githubusercontent.com/11875591/71680553-0273d280-2d50-11ea-977b-4d00c3518fad.png)
The contact attempts and and target notes queries do not actually filter by target id provided in input.
looks like every contact is returning just all of the contact attempts/notes.

**Comment by jakelowen** [comment]
Should be resolved with backend commit 7c630c18234b29848a3a2572d4c4a6f3b99e9666

Tested on production and seems good.
