### ISSUE TITLE
Trash task 0?

### ISSUE THREAD

**Issue by jakelowen** [gpsimpact/census-relational-organizing-frontend#130]
For future consideration:

From Colin:

> Currently, Internet access, comfort with writing in English, and non-English languages are all under Task 0, in-take. 
> 
> #2) Can these questions be added to profile instead and we trash Task 0?

**Comment by jrazmi** [comment]
I'm going to leave this alone for now.  Would be a pretty big database migration to get all those fields on contacts and I won't be able to do anything until the backend is ready for that.

**Comment by jakelowen** [comment]
Agreed. I think this one is out of scope for the timeframe of the project.
