### ISSUE TITLE
Module 4 revisions

### ISSUE THREAD

**Issue by jakelowen** [gpsimpact/census-relational-organizing-frontend#139]
Module 4 - add option: 
What method does this person prefer to fill out the form?
In-person, with the assistance of an official Census-taker
If yes, what language?
Other Language (Please specify)  - line text input

**Comment by jakelowen** [comment]
Please provide complete list of methods before we update module.

**Comment by CaptainTeft** [comment]
@jakelowen @jrazmi for now, let's go with:

Chinese (Mandarin)
Chinese (Cantonese)
English
Hindi
Hmong
Japanese
Khmer
Korean
Spanish
Other Language (please specify) - line text input

**Comment by jakelowen** [comment]
Added: 
![image](https://user-images.githubusercontent.com/5368008/73770500-27d67080-4742-11ea-90df-bef1a58e95ba.png)
