### ISSUE TITLE
Revisions to Module 5

### ISSUE THREAD

**Issue by jakelowen** [gpsimpact/census-relational-organizing-frontend#140]
Module 5 - add option:
What methods will this person use to reach out to others? Check all that apply
Letter or card

**Comment by jakelowen** [comment]
Please provide complete list of methods before we add.

**Comment by villahm206** [comment]
- Letter or card
- Text or messaging platform (WhatsApp, WeChat, Viber, etc.)
- Email
- Social Media (Facebook, Instagram, Snapchat, Twitter)
- Phone Call
- In-person gathering
- Volunteering with a local organization
- Other (Please specify)

**Comment by jakelowen** [comment]
added 
![image](https://user-images.githubusercontent.com/5368008/73770840-bc40d300-4742-11ea-88ba-d3eecaa7429b.png)
