### ISSUE TITLE
Organization not Alphabatized in "all teams" view

### ISSUE THREAD

**Issue by villahm206** [gpsimpact/census-relational-organizing-frontend#146]
<img width="836" alt="Screen Shot 2020-01-29 at 6 30 23 PM" src="https://user-images.githubusercontent.com/60158307/73415070-9db38580-42c5-11ea-9e63-bf32837bfbed.png">

**Comment by jakelowen** [comment]
@jrazmi - I just pushed another test to explicitly verify sort param on teams query works. Use as `{ input: { sort: { name: "ASC" } } }`
