### ISSUE TITLE
Modules on dashboard display in seemingly-random order

### ISSUE THREAD

**Issue by CaptainTeft** [gpsimpact/census-relational-organizing-frontend#158]
Can this be simply ordered alphabetically instead?
![random](https://user-images.githubusercontent.com/60598155/74887832-f14b4900-5330-11ea-9087-d3b6d8fa945c.png)

**Comment by jakelowen** [comment]
Fixed via backend deployment. 

![image](https://user-images.githubusercontent.com/5368008/74954561-e93ee800-53c8-11ea-9e83-4d0df4e9c180.png)
